(provide 'init-appearance)

(quelpa 'monokai-theme)
(quelpa 'zenburn-theme)
(quelpa 'base16-theme)
(quelpa 'dash)
(require 'dash)

;(load-theme 'monokai t)
(toggle-scroll-bar -1)
;(load-theme 'zenburn t)
;(load-theme 'wilson)
;(load-theme 'misterioso)
(setq base16-theme-256-color-source "colors")
;(load-theme 'base16-gruvbox-dark-soft t)
(load-theme 'base16-tomorrow-night t)
