(provide 'init-go)

(quelpa 'go-mode)
(quelpa 'go-eldoc)
(quelpa 'go-errcheck)
(quelpa 'gotest)

(add-hook 'go-mode-hook (lambda ()
			  ;(require 'golint)
			  (go-eldoc-setup)
			  (setq gofmt-command "goimports")
			  (add-hook 'before-save-hook 'gofmt-before-save)
			  (define-key go-mode-map (kbd "C-x x") 'go-run)
			  (define-key go-mode-map (kbd "C-x t") 'go-test-current-test)
                          (set (make-local-variable 'company-backends) '(company-go))
                          (company-mode)))
